#!/bin/bash

# CLI's
TERMINUS=terminus
GIT=git
DOCKER=docker

CONTAINER_NAME=wb-www-drupal
CONTAINER_NAME_DB=wb-www-mysql
DEFAULT_WWW_PORT=80
WBP_HOME=$(dirname $0)

# ----------------------------------------------------------

# Help screen
help() {
    echo "WB Pantheon Deployment script v0.1"
    echo "Usage: $0 <options>"
    echo "  options:"
    echo "     list                  List of remote pantheon sites"
    echo "     clone <site-name>     Clone site locally from pantheon web portal"
    echo "     up <site-name>        Run site locally in docker"
    echo "     down                  Stop site locally in docker"
    echo "     shell                 Enter in shell drupal container (wb-www-drupal)"
    echo "     logs                  Show last 150 log entries (wb-www-drupal)"
    echo "     uli                   Print Drupal admin login link (current local site)"
    echo "     ruli                  Print Drupal admin login link (remote site)"
    echo "     cr                    Drupal cache rebuild"
    echo "     composer              Run PHP composer inside wb-www-drupal container (This is useful when you want to install vendor libraries)"
    echo "     restore               Restore database from live site (wb-www-mysql)"
    echo "     dump                  Dump database from db to file"
    echo "     restoreFiles          Restore files from live site"
    echo "     dashboard             Print Pantheon dashboard link by given site name"
    echo "     conn                  Switch development environment between sftp and git"
    echo "     security              Disable or Enable security modules (securelogin and seckit)"
    echo 
    echo "Example 1: $0 list"
    echo "Example 2: $0 clone site-name"
    echo "Example 3: $0 up site-name"
    echo "Example 4: $0 down"
    echo "Example 5: $0 shell"
    echo "Example 6: $0 logs"
    echo "Example 7: $0 cr"
    echo "Example 8: $0 composer"
    echo "Example 9: $0 restore"
    echo "Example 10: $0 dump"
    echo "Example 11: $0 restoreFiles"
    echo "Example 12: $0 dashboard"
    echo "Example 13: $0 conn sft"
    echo "Example 14: $0 security enable"
}
# ----------------------------------------------------------

copy_to_clipboard() {
    local content="$1"
    if command -v pbcopy &>/dev/null; then
        echo "$content" | pbcopy
    elif command -v xclip &>/dev/null; then
        echo "$content" | xclip -selection clipboard
    else
        echo "Clipboard tool not found (pbcopy or xclip). Can't copy to clipboard." >&2
    fi
}

# ----------------------------------------------------------

site-list() {
    # #Authenticate Terminus
    $TERMINUS auth:login
    $TERMINUS site:list --format=json | grep -o '"name": "[^"]*' | grep -o '[^"]*$'
}

# ----------------------------------------------------------

site-up() {

    if [ "$ACTION_PARAM" == "" ]; then
        PS2="Select your site from local list 'sites/*' (number): "
        select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi
    
    if [ -d "sites/$ACTION_PARAM" ]; then    
        export SITE_NAME=$ACTION_PARAM
        export PORT=$DEFAULT_WWW_PORT

        $DOCKER compose up -d --force-recreate
    else
        echo "Site 'sites/$ACTION_PARAM' doesn't exists !"
        exit 1
    fi
}

# ----------------------------------------------------------

site-down() {
    $DOCKER compose stop
}

# ----------------------------------------------------------

composer() {

    # Run PHP composer inside drupal container
    $DOCKER exec -i $CONTAINER_NAME apk add git
    $DOCKER exec -i $CONTAINER_NAME apk add unzip
    $DOCKER exec -i $CONTAINER_NAME apk add patch
    $DOCKER exec -i $CONTAINER_NAME composer install --ignore-platform-req=ext-bcmath
}

# ----------------------------------------------------------

clone() {

    # #Authenticate Terminus
    $TERMINUS auth:login

    if [ "$ACTION_PARAM" == "" ]; then
        PS3="Select your site from pantheon (number): "
        select SNM in $($TERMINUS site:list --format=json | grep -o '"name": "[^"]*' | grep -o '[^"]*$')
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi

    export SITE_NAME=$ACTION_PARAM
    export PORT=$DEFAULT_WWW_PORT

    DIR="sites/$SITE_NAME"
    DIR_SITES="sites"
    
    SITE_ID=$($TERMINUS site:lookup $SITE_NAME)
    if [ $? -ne 0 ]; then
        exit $?
    fi

    if [ ! -d $DIR ]; then

        # create sites directory if doesn't exists
        mkdir -p $DIR
        
        echo "git clone" "ssh://codeserver.dev.$SITE_ID@codeserver.dev.$SITE_ID.drush.in:2222/~/repository.git -b master $DIR"
        $GIT clone ssh://codeserver.dev.$SITE_ID@codeserver.dev.$SITE_ID.drush.in:2222/~/repository.git -b master $DIR
        EXIT_CODE=$?

        # Check if the command was successful
        if [ $EXIT_CODE -ne 0 ]; then
            echo "Error: git clone failed with exit code $EXIT_CODE"
            exit $?
        fi

        placeholder="\${DB_NAME}"
        cp config/settings.local.php $DIR_SITES/$SITE_NAME-settings.local.php
        sed -i '' "s|$placeholder|$SITE_NAME|g" "$DIR_SITES/$SITE_NAME-settings.local.php"

        # link settings.php
        rm -f $DIR/web/sites/default/settings.local.php
        ln $DIR_SITES/$SITE_NAME-settings.local.php $DIR/web/sites/default/settings.local.php
        
        # Run php composer inside drupal container
        # up containers
        $DOCKER compose up -d --force-recreate
        composer;
        
        PS3="Select 1 (Yes) 2 (No): "
        echo "Do you want to restore database from pantheon ?"
        select yn in "Yes" "No"; do
            case $yn in
            Yes)
                db-restore;
                break
                ;;
            No) exit ;;
            esac
        done
    else
        echo "Site '$DIR' already exists!, Do you want to update from git ?"
        select yn in "Yes" "No"; do
            case $yn in
            Yes)
                $GIT -C $DIR pull;
                break
                ;;
            No) exit ;;
            esac
        done
    fi
}

# ----------------------------------------------------------

logs() {
    $DOCKER logs -tf --tail=150 $CONTAINER_NAME
}

# ----------------------------------------------------------

uli() {
    # $DOCKER exec -i $CONTAINER_NAME drush uli
    input=$($DOCKER exec -i $CONTAINER_NAME drush uli)
    output=$(echo "$input" | sed 's|http://default|http://wb-pantheon.local|')

    copy_to_clipboard "$output"
    echo "$output"
}

# ----------------------------------------------------------

ruli() {

    if [ "$ACTION_PARAM" == "" ]; then
        PS2="Select site to generate admin link: "
        select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi

    input=$(terminus drush $ACTION_PARAM.dev -- uli)
    output=$(echo "$input" | sed 's|http://default|http://wb-pantheon.local|')

    copy_to_clipboard "$output"
    echo "$output"
}


# ----------------------------------------------------------

cr() {
    $DOCKER exec -i $CONTAINER_NAME drush cr
}

# ----------------------------------------------------------

dashboard-link() {

    if [ "$ACTION_PARAM" == "" ]; then
        PS2="Select site to download database dump (number): "
        select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi

    SITE_NAME=$ACTION_PARAM
    SITE_ID=$(terminus site:info $SITE_NAME | sed -n 's/^  ID[[:space:]]*\(.*\)/\1/p')
    output="https://dashboard.pantheon.io/sites/${SITE_ID}"
    output=$(echo "$output" | xargs)
    copy_to_clipboard "$output"
    echo "$output"
}

# ----------------------------------------------------------

connection() {

    if [ "$ACTION_PARAM" == "" ]; then
        echo "Select one of the connection sftp or git"
        exit 1
    fi

    PS2="Select site to download database dump (number): "
    select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
    do
        SITE_NAME=$SNM
        break;
    done
    
    echo connection:set $SITE_NAME.dev $ACTION_PARAM
    $TERMINUS connection:set $SITE_NAME.dev $ACTION_PARAM
}

# ----------------------------------------------------------

security() {

    if [ "$ACTION_PARAM" == "" ]; then
        echo "Select one of the parameters enable or disable"
        exit 1
    fi

    
    echo Security modules $ACTION_PARAM
    if [ "$ACTION_PARAM" == "enable" ]; then
        $DOCKER exec -i $CONTAINER_NAME drush pm:install securelogin
        $DOCKER exec -i $CONTAINER_NAME drush pm:install seckit
    fi
    if [ "$ACTION_PARAM" == "disable" ]; then
        $DOCKER exec -i $CONTAINER_NAME drush pm:uninstall securelogin
        $DOCKER exec -i $CONTAINER_NAME drush pm:uninstall seckit
    fi
}

# ----------------------------------------------------------

db-dump() {
   
    if [ "$ACTION_PARAM" == "" ]; then
        PS2="Select site to download database dump (number): "
        select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi

    SITE_NAME=$ACTION_PARAM
    DIR_DB="db"

    echo "Export... $DIR_DB/$SITE_NAME-db.sql.gz"
    $DOCKER exec -i $CONTAINER_NAME_DB mysqldump -uroot $SITE_NAME | gzip > $DIR_DB/$SITE_NAME-db.sql.gz 
}

# ----------------------------------------------------------

db-restore() {

    if [ "$ACTION_PARAM" == "" ]; then
        PS2="Select site to download database dump (number): "
        select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi

    $TERMINUS local:getLiveDb $ACTION_PARAM
    if [ $? -ne 0 ]; then
        exit $?
    fi
    
    mkdir -p db
    mv $HOME/pantheon-local-copies/db/$ACTION_PARAM-db.tgz db
    echo "Extracting db/$ACTION_PARAM-db.tgz..."
    gunzip db/$ACTION_PARAM-db.tgz 

    echo "Importing db/$ACTION_PARAM-db.tgz into $CONTAINER_NAME_DB" 
    # Check if the database exists and create it if not
    $DOCKER exec -i $CONTAINER_NAME_DB mysql -uroot --execute="CREATE DATABASE IF NOT EXISTS \`$ACTION_PARAM\`;"
    $DOCKER exec -i $CONTAINER_NAME_DB mysql -uroot --force $ACTION_PARAM < db/$ACTION_PARAM-db.tar 
    $DOCKER exec -i $CONTAINER_NAME_DB mysql -uroot --execute="USE $ACTION_PARAM; UPDATE config SET data = REPLACE(data, '\"preprocess\";b:1', '\"preprocess\";b:0') WHERE name = 'system.performance';"
    

}

# ----------------------------------------------------------

file-restore() {

    if [ "$ACTION_PARAM" == "" ]; then
        PS2="Select site to download files (number): "
        select SNM in $(find sites/ -maxdepth 1 -type d ! -name 'sites' -exec basename {} \;)
        do
            ACTION_PARAM=$SNM
            break;
        done
    fi

    $TERMINUS local:getLiveFiles $ACTION_PARAM
    if [ $? -ne 0 ]; then
        exit $?
    fi
    
    mv $HOME/pantheon-local-copies/files/$ACTION_PARAM-files.tgz sites/$ACTION_PARAM/web/sites/default
    echo "Extracting db/$ACTION_PARAM-files.tgz..."
    tar zxvf sites/$ACTION_PARAM/web/sites/default/$ACTION_PARAM-files.tgz -C sites/$ACTION_PARAM/web/sites/default
    rm -rf  sites/$ACTION_PARAM/web/sites/default/files
    mv sites/$ACTION_PARAM/web/sites/default/files_live sites/$ACTION_PARAM/web/sites/default/files
}

# ----------------------------------------------------------

summary() {
    echo
    echo "You should add local domain entry in your /etc/hosts file."
    echo "sudo vi /etc/hosts"
    echo "127.0.0.1   wb-pantheon.local"
    echo 
    echo "Visit: http://wb-pantheon.local"
    echo 
    echo 
    echo "Useful commands:"
    echo "Enter in drupal container shell: '$0 shell'"
    echo "Inside container you can use drush: 'drush cache:rebuild'"
    echo 
    echo "Admin URL"
    $DOCKER exec -i $CONTAINER_NAME drush uli
    echo 
}

# ----------------------------------------------------------

main () {

    POSITIONAL=()
    while [[ $# -gt 0 ]]; do
        key="$1"

        case $key in
        clone)
            ACTION=clone
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        list)
            ACTION=list
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        up)
            ACTION=up
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        down)
            ACTION=down
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        shell)
            ACTION=shell
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        composer)
            ACTION=composer
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        logs)
            ACTION=logs
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        uli)
            ACTION=uli
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        ruli)
            ACTION=ruli
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        cr)
            ACTION=cr
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        dump)
            ACTION=dump
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        restore)
            ACTION=restore
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        restoreFiles)
            ACTION=restoreFiles
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        dashboard)
            ACTION=dashboard
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        conn)
            ACTION=conn
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        security)
            ACTION=security
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
        esac
    done

    set -- "${POSITIONAL[@]}" # restore positional parameters

    # Here is positional parameters tail. Basically the last command line argument(s).
    TAIL=$1

    # Check dependency. If 'docker' is here.
    # Normally docker should be here but who knows :)
    if ! hash $DOCKER &>/dev/null; then
        echo "Docker is not installed on Host computer !, Please make sure 'docker' CLI is accessible from shell"
        exit 1
    fi

    # Check dependency. If 'terminus' is here.
    # Normally terminus should be here but who knows :)
    if ! hash $TERMINUS &>/dev/null; then
        echo "Terminus is not installed on Host computer. Terminus is a command line interface that provides advanced interaction with Pantheon."
        echo "You can install from here: https://docs.pantheon.io/terminus/install"
        exit 1
    fi

    # Check dependency. If 'git' is here.
    # Normally git should be here but who knows :)
    if ! hash $GIT &>/dev/null; then
        echo "Git is not installed on Host computer. That's weird"
        exit 1
    fi

    # Check action parameter
    if [ "$ACTION" == "" ]; then
        help
        echo "Action must be specified in command line argument !"
        exit 1
    else

        # clone action
        if [ "$ACTION" == "clone" ]; then
            clone;
            summary;
        fi

        # list action
        if [ "$ACTION" == "list" ]; then
            site-list;
        fi

        # up action
        if [ "$ACTION" == "up" ]; then
            site-up;
            summary;
        fi

        # down action
        if [ "$ACTION" == "down" ]; then
            site-down;
        fi

        # shell action
        if [ "$ACTION" == "shell" ]; then
            # $DOCKER exec -i $CONTAINER_NAME ln -s /opt/drupal/web/vendor/drush/drush/drush /opt/drupal/vendor/bin/drush
            $DOCKER exec -it $CONTAINER_NAME sh
        fi
        
        # composer action
        if [ "$ACTION" == "composer" ]; then
            composer;
        fi

        # logs action
        if [ "$ACTION" == "logs" ]; then
            logs;
        fi

        # uli action
        if [ "$ACTION" == "uli" ]; then
            uli;
        fi

        # ruli action
        if [ "$ACTION" == "ruli" ]; then
            ruli;
        fi

        # cr action
        if [ "$ACTION" == "cr" ]; then
            cr;
        fi

        # restore action
        if [ "$ACTION" == "restore" ]; then
            db-restore;
        fi

        # restore action
        if [ "$ACTION" == "dump" ]; then
            db-dump;
        fi

        # restore action
        if [ "$ACTION" == "restoreFiles" ]; then
            file-restore;
        fi

        # dashboard action
        if [ "$ACTION" == "dashboard" ]; then
            dashboard-link;
        fi

        # connection action
        if [ "$ACTION" == "conn" ]; then
            connection;
        fi

        # security action
        if [ "$ACTION" == "security" ]; then
            security;
        fi

        exit 0
    fi

    help;
}

main "$@"



